services:
  db:
    container_name: postgres-db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=aq54
    ports:
      - "5433:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - my-network

  backend:
    container_name: backend-nestjs
    build:
      context: ./aq54-backend
    ports:
      - "8000:8000"
    networks:
      - my-network
    depends_on:
      - db

  frontend:
    container_name: frontend-reactjs
    build:
      context: ./aq54-frontend
    ports:
      - 5173:5173
    networks:
      - my-network
    depends_on:
      - backend

  pgadmin:
    container_name: pg-admin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - my-network
    depends_on:
      - db

volumes:
  database:

networks:
  my-network:
    driver: bridge
